### ISSUE TITLE
themax pitch wildcard problem

### ISSUE THREAD

**Issue by jacekiwaszko1** [craigsapp/humextra#15]
`.?` does not work.

```
**kern
8aL
8fJ
8bL
8fJ
8ccL
8fJ
8ccL
8fJ
*-
```

This search works:
`themax -p "a . b . c . c" data4.tindex `
output:
```
data4.krn::1	ZC=	JA F B F C F C F 	M
```
This one doesn't:
`themax -p "a .? b .? c .? c" data4.tindex`

**Comment by craigsapp** [comment]
Should now work:

```bash
$ bin/themax -p "a . b . c . c" data4.tindex 
z.krn::1	ZC=	JA F B F C F C F 	M
$ bin/themax -p "a .? b .? c .? c" data4.tindex
z.krn::1	ZC=	JA F B F C F C F 	M
```

The problem was that the expansion into a regular express had a space remove which should not have been.  The `themax --cleaned` option can be used to examined the final regular expression that will be used to search the data:

Now it is correct:
```
Final Regular Expression: J[^\t]*(?:A) (?:[A-G][#-]* )?(?:B) (?:[A-G][#-]* )?(?:C) (?:[A-G][#-]* )?(?:C)[ \t]
```

Here is what it used to be:

```
Final Regular Expression: J[^\t]*(?:A) (?:[A-G][#-]*)?(?:B) (?:[A-G][#-]*)?(?:C) (?:[A-G][#-]*)?(?:C)[ \t]
```
