### ISSUE TITLE
hum2xml: always include slash attribute in grace tag?

### ISSUE THREAD

**Issue by pvankranenburg** [craigsapp/humextra#8]
hum2xml does not add the `slash` attribute to the `<grace />` tag if there is no slash intended. This leaves the decision to add a slash to whatever musicxml parser. I would suggest always to include the slash attribute. So, either slash="yes" or slash="no". Any objection to that?

**Comment by craigsapp** [comment]
Yes, there should definitely be a way to differentiate between slashed and non-slashed grace notes.

For going from Humdrum to MusicXML with `hum2xml`, this currently already seems to be possible.  In Humdrum, add `q` when you want the gracenote to have a slash, and `qq` when you want the gracenote to not have a slash.

Here is a test example:

```
**kern
*clefG2
*k[]
*M4/4
=1
8qg/
2f
8qqg/
2a
==
*-
```

This converts to MusicXML with `hum2xml` like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 2.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="2.0">
	<part-list>
		<score-part id="P1">
			<part-name></part-name>
		</score-part>
	</part-list>

	<part id="P1">
		<measure number="1">
			<attributes>
				<divisions>2</divisions>
			</attributes>
			<attributes>
				<clef>
					<sign>G</sign>
					<line>2</line>
				</clef>
			</attributes>
			<attributes>
				<key>
					<fifths>0</fifths>
				</key>
			</attributes>
			<attributes>
				<time>
					<beats>4</beats>
					<beat-type>4</beat-type>
				</time>
			</attributes>
			<note>
				<grace slash="yes"/>
				<pitch>
					<step>G</step>
					<octave>4</octave>
				</pitch>
				<voice>1</voice>
				<type>eighth</type>
				<stem>up</stem>
			</note>
			<note>
				<pitch>
					<step>F</step>
					<octave>4</octave>
				</pitch>
				<duration>4</duration>
				<voice>1</voice>
				<type>half</type>
			</note>
			<note>
				<grace/>
				<pitch>
					<step>G</step>
					<octave>4</octave>
				</pitch>
				<voice>1</voice>
				<type>eighth</type>
				<stem>up</stem>
			</note>
			<note>
				<pitch>
					<step>A</step>
					<octave>4</octave>
				</pitch>
				<duration>4</duration>
				<voice>1</voice>
				<type>half</type>
			</note>
		</measure>
	</part>
</score-partwise>
```

And loading into MuseScore:

<img width="629" alt="screen shot 2018-07-27 at 11 57 07 am" src="https://user-images.githubusercontent.com/3487289/43314709-061ccec2-9194-11e8-806d-7ebaeb2738c4.png">


----------------------

However, I notice that the converters from MusicXML into Humdrum did not preserve the difference between slashed and unslashed grace notes.  I have just added this funcionality to both of them: (1) the program `musicxml2hum` which is part of [humlib](http://humlib.humdrum.org), and (2) `xml2hum` whihc is part of [Humdrum Extras](http://github.com/craigsapp/humextra).  The `musicxml2hum` program is an eventual replacement for `xml2hum` (so preferably use `musicxml2hum` for converting MusicXML into Humdrum, although I have fixed both with regards to grace note slashes).

Here is the update for `musicxml2hum`:   

https://github.com/craigsapp/humlib/commit/02418c040eb45e8299c79985a0b5d7a50d45c3da

This version of the converter is used in verovio-humdrum-viewer, so dragging and dropping the following MusicXML data file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 3.1 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="3.1">
  <work>
    <work-title>Title</work-title>
    </work>
  <identification>
    <creator type="composer">Composer</creator>
    <encoding>
      <software>MuseScore 2.2.1</software>
      <encoding-date>2018-07-27</encoding-date>
      <supports element="accidental" type="yes"/>
      <supports element="beam" type="yes"/>
      <supports element="print" attribute="new-page" type="yes" value="yes"/>
      <supports element="print" attribute="new-system" type="yes" value="yes"/>
      <supports element="stem" type="yes"/>
      </encoding>
    </identification>
  <defaults>
    <scaling>
      <millimeters>7.05556</millimeters>
      <tenths>40</tenths>
      </scaling>
    <page-layout>
      <page-height>1683.36</page-height>
      <page-width>1190.88</page-width>
      <page-margins type="even">
        <left-margin>56.6929</left-margin>
        <right-margin>56.6929</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      <page-margins type="odd">
        <left-margin>56.6929</left-margin>
        <right-margin>56.6929</right-margin>
        <top-margin>56.6929</top-margin>
        <bottom-margin>113.386</bottom-margin>
        </page-margins>
      </page-layout>
    <word-font font-family="FreeSerif" font-size="10"/>
    <lyric-font font-family="FreeSerif" font-size="11"/>
    </defaults>
  <credit page="1">
    <credit-words default-x="595.44" default-y="1626.67" justify="center" valign="top" font-size="24">Title</credit-words>
    </credit>
  <credit page="1">
    <credit-words default-x="1134.19" default-y="1526.67" justify="right" valign="bottom" font-size="12">Composer</credit-words>
    </credit>
  <part-list>
    <score-part id="P1">
      <part-name>Piano</part-name>
      <part-abbreviation>Pno.</part-abbreviation>
      <score-instrument id="P1-I1">
        <instrument-name>Piano</instrument-name>
        </score-instrument>
      <midi-device id="P1-I1" port="1"></midi-device>
      <midi-instrument id="P1-I1">
        <midi-channel>1</midi-channel>
        <midi-program>1</midi-program>
        <volume>78.7402</volume>
        <pan>0</pan>
        </midi-instrument>
      </score-part>
    </part-list>
  <part id="P1">
    <measure number="1" width="1077.49">
      <print>
        <system-layout>
          <system-margins>
            <left-margin>0.00</left-margin>
            <right-margin>-0.00</right-margin>
            </system-margins>
          <top-system-distance>170.00</top-system-distance>
          </system-layout>
        </print>
      <attributes>
        <divisions>1</divisions>
        <key>
          <fifths>0</fifths>
          </key>
        <time>
          <beats>4</beats>
          <beat-type>4</beat-type>
          </time>
        <clef>
          <sign>G</sign>
          <line>2</line>
          </clef>
        </attributes>
      <note default-x="71.29" default-y="-30.00">
        <grace slash="yes"/>
        <pitch>
          <step>G</step>
          <octave>4</octave>
          </pitch>
        <voice>1</voice>
        <type>eighth</type>
        <stem>up</stem>
        </note>
      <note default-x="89.73" default-y="-35.00">
        <pitch>
          <step>F</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>up</stem>
        </note>
      <note default-x="559.69" default-y="-30.00">
        <grace/>
        <pitch>
          <step>G</step>
          <octave>4</octave>
          </pitch>
        <voice>1</voice>
        <type>eighth</type>
        <stem>up</stem>
        </note>
      <note default-x="578.13" default-y="-25.00">
        <pitch>
          <step>A</step>
          <octave>4</octave>
          </pitch>
        <duration>2</duration>
        <voice>1</voice>
        <type>half</type>
        <stem>up</stem>
        </note>
      <barline location="right">
        <bar-style>light-heavy</bar-style>
        </barline>
      </measure>
    </part>
  </score-partwise>
```

onto the [VHV](http://verovio.humdrum.org) website, which will convert the slashed/unslashed grace notes properly:

<img width="814" alt="screen shot 2018-07-27 at 11 08 32 am" src="https://user-images.githubusercontent.com/3487289/43315021-02ac11ac-9195-11e8-8a4d-f1dac236291c.png">

To update `musicxml2hum` with git, do these commands within the `humlib` directory:

```bash
git pull
make
```

This will compile the program and place it in `bin/musicxml2hum`.  If you want to make the program available in any directory, then also type:

```bash
make install
```

This will copy the humlib command-line tools to `/usr/local/bin` (which is presumably present in your MacOS/linux/Cygwin installation, and also presumes that your command-path includes `/usr/local/bin`).

For humextra's `xml2hum`,  there are several ways that it can be installed, so I won't mention how unless needed.

Here is the commit that allows slashed/unslashed gracenotes in the `xml2hum` command: https://github.com/craigsapp/humextra/commit/2a82b58f0913c38119e1536f99fefd7d0f93bef2

**Comment by pvankranenburg** [comment]
Thanks a lot for looking into this.

Indeed, I use `q` and `qq` in the way you indicate, `q` for no slash and `qq` for slash.

My question refers to the output of `hum2xml`. Currently it does:

`q` -> `<grace />`
`qq` -> `<grace slash="yes">`

My suggestion is to have this instead:

`q` -> `<grace slash="no"/>`
`qq` -> `<grace slash="yes"/>`

So, make both cases explicit. That doesn't leave the decision to add a slash to whatever musicxml parser.

But maybe there are reasons not to do this, I don't oversee at the moment?

**Comment by craigsapp** [comment]
Doing the mapping:

```
q -> <grace slash="yes"/>
qq -> <grace slash="no"/>
```

is reasonable.   Most renderers would probably assume `grace@slash="no"` if there is no slash attribute given.  But it is safest to explicitly give the `no` state as well.   I have added it to `xml2hum` in commit https://github.com/craigsapp/humextra/commit/5434470fa1fecf5b01453920269355fc821d4d53

Note that `q` actually means "unaccented grace note" and `qq` means  "accented grace note", and these happen to map to a slashed and non-slashed grace note according to modern notation conventions.

Test data:

```

**kern
*clefG2
*k[]
*M4/4
=1
8qg/
2f
8qqg/
2a
==
*-
```

Now produces `slash="no"` in the MusicXML conversion with hum2xml:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 2.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="2.0">
	<part-list>
		<score-part id="P1">
			<part-name></part-name>
		</score-part>
	</part-list>

	<part id="P1">
		<measure number="1">
			<attributes>
				<divisions>2</divisions>
			</attributes>
			<attributes>
				<clef>
					<sign>G</sign>
					<line>2</line>
				</clef>
			</attributes>
			<attributes>
				<key>
					<fifths>0</fifths>
				</key>
			</attributes>
			<attributes>
				<time>
					<beats>4</beats>
					<beat-type>4</beat-type>
				</time>
			</attributes>
			<note>
				<grace slash="yes"/>
				<pitch>
					<step>G</step>
					<octave>4</octave>
				</pitch>
				<voice>1</voice>
				<type>eighth</type>
				<stem>up</stem>
			</note>
			<note>
				<pitch>
					<step>F</step>
					<octave>4</octave>
				</pitch>
				<duration>4</duration>
				<voice>1</voice>
				<type>half</type>
			</note>
			<note>
				<grace slash="no"/>
				<pitch>
					<step>G</step>
					<octave>4</octave>
				</pitch>
				<voice>1</voice>
				<type>eighth</type>
				<stem>up</stem>
			</note>
			<note>
				<pitch>
					<step>A</step>
					<octave>4</octave>
				</pitch>
				<duration>4</duration>
				<voice>1</voice>
				<type>half</type>
			</note>
		</measure>
	</part>
</score-partwise>
```


Loading the above MusicXML data into MuseScore 2.2:

<img width="629" alt="screen shot 2018-07-27 at 11 48 42 pm" src="https://user-images.githubusercontent.com/3487289/43347864-7bc9f628-91f7-11e8-8bce-cd124916d129.png">

**Comment by craigsapp** [comment]
Reminder on how to update humdrum extras:  Typically humdrum extras should be installed with humdrum-tools:

https://github.com/humdrum-tools/humdrum-tools

To update:

```bash
cd $(which keycor | sed 's/humextra.*//')
make update
make
```

The first line will change directory to the base installation of humdrum-tools.  The second line will download the new code, and the third line will recompile everything.  A minimal compile (which would not compile the external libraries again), would be:

```bash
cd $(which keycor | sed 's/humextra.*//')
make update
cd humextra
make -f Makefile.library library
make hum2xml
```
